In [3]:
import pandas as pd
import os

## data 자료 형태 파악하기
dir = "./data/" # 현재 디렉토리의 data 파일 안에 csv파일들 들어있으므로 편의상 변수로 지정

DIVIDER = '\n----------------------------------------------------------------\n' # 프린트했을 때 보기 편하게 선 긋기
listdir = [f for f in os.listdir(dir) if not f.startswith('.')]
print(listdir) # 현재 디렉토리의 data 파일 안에 있는 파일명 확인

['olist_sellers_dataset.csv', 'product_category_name_translation.csv', 'olist_orders_dataset.csv', 'olist_order_items_dataset.csv', 'olist_customers_dataset.csv', 'olist_geolocation_dataset.csv', 'olist_order_payments_dataset.csv', 'olist_order_reviews_dataset.csv', 'olist_products_dataset.csv']

In [10]:
## 9개 csv파일 데이터 읽기
cust = pd.read_csv(dir + 'olist_customers_dataset.csv')
geoloc = pd.read_csv(dir + 'olist_geolocation_dataset.csv')
order_items = pd.read_csv(dir + 'olist_order_items_dataset.csv')
payments = pd.read_csv(dir + 'olist_order_payments_dataset.csv')
reviews = pd.read_csv(dir + 'olist_order_reviews_dataset.csv')
orders = pd.read_csv(dir + 'olist_orders_dataset.csv')
products = pd.read_csv(dir + 'olist_products_dataset.csv')
sellers = pd.read_csv(dir + 'olist_sellers_dataset.csv')
translation = pd.read_csv(dir + 'product_category_name_translation.csv')

In [24]:
file_names = [cust, geoloc, order_items, payments, reviews, orders, products, sellers]

## 물품 카테고리명 변경

In [11]:
products = products.merge(translation, on='product_category_name').drop('product_category_name', axis=1)

In [35]:
products['product_category_name_english'].nunique() # 유니크 개수 = 71개

71

## info()로 각 파일별 데이터 타입 파악

In [25]:
for file in file_names:
    print(DIVIDER)
    file.info() # 각 파일들을 한 개씩 읽어서 info 함수로 자료형과 크기 파악

------------------------------------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
customer_id                 99441 non-null object
customer_unique_id          99441 non-null object
customer_zip_code_prefix    99441 non-null int64
customer_city               99441 non-null object
customer_state              99441 non-null object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

------------------------------------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
geolocation_zip_code_prefix    1000163 non-null int64
geolocation_lat                1000163 non-null float64
geolocation_lng                1000163 non-null float64
geolocation_city               1000163 non-null object
geolocation_state              1000163 non-null object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

------------------------------------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 6 columns):
order_id         112650 non-null object
order_item_id    112650 non-null int64
product_id       112650 non-null object
seller_id        112650 non-null object
price            112650 non-null float64
freight_value    112650 non-null float64
dtypes: float64(2), int64(1), object(3)
memory usage: 5.2+ MB

------------------------------------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
order_id                103886 non-null object
payment_sequential      103886 non-null int64
payment_type            103886 non-null object
payment_installments    103886 non-null int64
payment_value           103886 non-null float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

------------------------------------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
review_id                  100000 non-null object
order_id                   100000 non-null object
review_score               100000 non-null int64
review_comment_title       11715 non-null object
review_comment_message     41753 non-null object
review_creation_date       100000 non-null object
review_answer_timestamp    100000 non-null object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

------------------------------------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
order_id                         99441 non-null object
customer_id                      99441 non-null object
order_status                     99441 non-null object
order_purchase_timestamp         99441 non-null object
order_approved_at                99281 non-null object
order_delivered_carrier_date     97658 non-null object
order_delivered_customer_date    96476 non-null object
order_estimated_delivery_date    99441 non-null object
dtypes: object(8)
memory usage: 6.1+ MB

------------------------------------------

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32328 entries, 0 to 32327
Data columns (total 9 columns):
product_id                       32328 non-null object
product_name_lenght              32328 non-null float64
product_description_lenght       32328 non-null float64
product_photos_qty               32328 non-null float64
product_weight_g                 32327 non-null float64
product_length_cm                32327 non-null float64
product_height_cm                32327 non-null float64
product_width_cm                 32327 non-null float64
product_category_name_english    32328 non-null object
dtypes: float64(7), object(2)
memory usage: 2.5+ MB

------------------------------------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
seller_id                 3095 non-null object
seller_zip_code_prefix    3095 non-null int64
seller_city               3095 non-null object
seller_state              3095 non-null object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

## nunique()로 개수 파악

In [33]:
for file in file_names:
    print(DIVIDER)
    print('파일의 행렬 구조 = ',file.shape)
    print(file.nunique())

------------------------------------------

파일의 행렬 구조 =  (99441, 5)
customer_id                 99441
customer_unique_id          96096
customer_zip_code_prefix    14994
customer_city                4119
customer_state                 27
dtype: int64

------------------------------------------

파일의 행렬 구조 =  (1000163, 5)
geolocation_zip_code_prefix     19015
geolocation_lat                717358
geolocation_lng                717613
geolocation_city                 8011
geolocation_state                  27
dtype: int64

------------------------------------------

파일의 행렬 구조 =  (112650, 6)
order_id         98666
order_item_id       21
product_id       32951
seller_id         3095
price             5968
freight_value     6999
dtype: int64

------------------------------------------

파일의 행렬 구조 =  (103886, 5)
order_id                99440
payment_sequential         29
payment_type                5
payment_installments       24
payment_value           29077
dtype: int64

------------------------------------------

파일의 행렬 구조 =  (100000, 7)
review_id                  99173
order_id                   99441
review_score                   5
review_comment_title        4600
review_comment_message     36921
review_creation_date         637
review_answer_timestamp    99010
dtype: int64

------------------------------------------

파일의 행렬 구조 =  (99441, 8)
order_id                         99441
customer_id                      99441
order_status                         8
order_purchase_timestamp         98875
order_approved_at                90733
order_delivered_carrier_date     81018
order_delivered_customer_date    95664
order_estimated_delivery_date      459
dtype: int64

------------------------------------------

파일의 행렬 구조 =  (32328, 9)
product_id                       32328
product_name_lenght                 66
product_description_lenght        2960
product_photos_qty                  19
product_weight_g                  2201
product_length_cm                   99
product_height_cm                  102
product_width_cm                    95
product_category_name_english       71
dtype: int64

------------------------------------------

파일의 행렬 구조 =  (3095, 4)
seller_id                 3095
seller_zip_code_prefix    2246
seller_city                611
seller_state                23
dtype: int64

## head()로 데이터 살펴보기

In [27]:
for file in file_names:
    print(DIVIDER)
    print(file.head())

------------------------------------------

                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP

------------------------------------------

   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292
1                         1046       -23.546081       -46.644820
2                         1046       -23.546129       -46.642951
3                         1041       -23.544392       -46.639499
4                         1035       -23.541578       -46.641607

  geolocation_city geolocation_state
0        sao paulo                SP
1        sao paulo                SP
2        sao paulo                SP
3        sao paulo                SP
4        sao paulo                SP

------------------------------------------

                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1

                         product_id                         seller_id   price  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202   58.90
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36  239.90
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d  199.00
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4   12.99
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87  199.90

   freight_value
0          13.29
1          19.93
2          17.87
3          12.79
4          18.14

------------------------------------------

                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71
3                     8         107.78
4                     2         128.45

------------------------------------------

                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

   review_score review_comment_title  \
0             4                  NaN
1             5                  NaN
2             5                  NaN
3             5                  NaN
4             5                  NaN

                              review_comment_message review_creation_date  \
0                                                NaN  2018-01-18 00:00:00
1                                                NaN  2018-03-10 00:00:00
2                                                NaN  2018-02-17 00:00:00
3              Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
4  Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00

  review_answer_timestamp
0     2018-01-18 21:46:59
1     2018-03-11 03:05:13
2     2018-02-18 14:36:24
3     2017-04-21 22:02:06
4     2018-03-02 10:26:53

------------------------------------------

                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00
3           2017-12-15 00:00:00
4           2018-02-26 00:00:00

------------------------------------------

                         product_id  product_name_lenght  \
0  1e9e8ef04dbcff4541ed26657ea517e5                 40.0
1  6a2fb4dd53d2cdb88e0432f1284a004c                 39.0
2  0d009643171aee696f4733340bc2fdd0                 52.0
3  b1eae565a61935e0011ee7682fef9dc9                 49.0
4  8da90b37f0fb171b4877c124f965b1f6                 56.0

   product_description_lenght  product_photos_qty  product_weight_g  \
0                       287.0                 1.0             225.0
1                       346.0                 2.0             400.0
2                       150.0                 1.0             422.0
3                       460.0                 2.0             267.0
4                       733.0                 3.0             377.0

   product_length_cm  product_height_cm  product_width_cm  \
0               16.0               10.0              14.0
1               27.0                5.0              20.0
2               21.0               16.0              18.0
3               17.0               13.0              17.0
4               18.0               13.0              15.0

  product_category_name_english
0                     perfumery
1                     perfumery
2                     perfumery
3                     perfumery
4                     perfumery

------------------------------------------

                          seller_id  seller_zip_code_prefix  \
0  3442f8959a84dea7ee197c632cb2df15                   13023
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914

         seller_city seller_state
0           campinas           SP
1         mogi guacu           SP
2     rio de janeiro           RJ
3          sao paulo           SP
4  braganca paulista           SP

## describe()로 연속형들 분포 파악

In [28]:
for file in file_names:
    print(DIVIDER)
    print(file.describe())

------------------------------------------

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

------------------------------------------

       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                 1.000163e+06     1.000163e+06     1.000163e+06
mean                  3.657417e+04    -2.117615e+01    -4.639054e+01
std                   3.054934e+04     5.715866e+00     4.269748e+00
min                   1.001000e+03    -3.660537e+01    -1.014668e+02
25%                   1.107500e+04    -2.360355e+01    -4.857317e+01
50%                   2.653000e+04    -2.291938e+01    -4.663788e+01
75%                   6.350400e+04    -1.997962e+01    -4.376771e+01
max                   9.999000e+04     4.506593e+01     1.211054e+02

------------------------------------------

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

------------------------------------------

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

------------------------------------------

        review_score
count  100000.000000
mean        4.070890
std         1.359663
min         1.000000
25%         4.000000
50%         5.000000
75%         5.000000
max         5.000000

------------------------------------------

                                order_id                       customer_id  \
count                              99441                             99441
unique                             99441                             99441
top     3eb9297e6fd8ebcad90e3d436f378207  aee6316af49a9075ee0cce8c83a90866
freq                                   1                                 1

       order_status order_purchase_timestamp    order_approved_at  \
count         99441                    99441                99281
unique            8                    98875                90733
top       delivered      2018-08-02 12:05:26  2018-02-27 04:31:10
freq          96478                        3                    9

       order_delivered_carrier_date order_delivered_customer_date  \
count                         97658                         96476
unique                        81018                         95664
top             2018-05-09 15:48:00           2018-05-14 20:02:44
freq                             47                             3

       order_estimated_delivery_date
count                          99441
unique                           459
top              2017-12-20 00:00:00
freq                             522

------------------------------------------

       product_name_lenght  product_description_lenght  product_photos_qty  \
count         32328.000000                32328.000000        32328.000000
mean             48.474078                  771.520168            2.188815
std              10.246388                  635.180062            1.736746
min               5.000000                    4.000000            1.000000
25%              42.000000                  339.000000            1.000000
50%              51.000000                  595.000000            1.000000
75%              57.000000                  972.000000            3.000000
max              76.000000                 3992.000000           20.000000

       product_weight_g  product_length_cm  product_height_cm  \
count      32327.000000       32327.000000       32327.000000
mean        2276.960807          30.856498          16.955950
std         4279.734063          16.958460          13.637246
min            0.000000           7.000000           2.000000
25%          300.000000          18.000000           8.000000
50%          700.000000          25.000000          13.000000
75%         1900.000000          38.000000          20.500000
max        40425.000000         105.000000         105.000000

       product_width_cm
count      32327.000000
mean          23.208464
std           12.080665
min            6.000000
25%           15.000000
50%           20.000000
75%           30.000000
max          118.000000

------------------------------------------

       seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000

## 1. payments 파일 탐색

In [57]:
payments.info()
payments.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
order_id                103886 non-null object
payment_sequential      103886 non-null int64
payment_type            103886 non-null object
payment_installments    103886 non-null int64
payment_value           103886 non-null float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

order_id                99440
payment_sequential         29
payment_type                5
payment_installments       24
payment_value           29077
dtype: int64

In [50]:

print("중복된 ID : {}".format(payments.shape[0]-len(payments['order_id'].unique())))

print(len(payments['order_id'].unique()))

중복된 ID : 4446
99440

In [52]:
duplicates = payments.groupby('order_id').count().sort_values(by='payment_value',ascending=False)['payment_value']
print("중복된 ID 상위 5개 별 중복된 개수 : {}".format(duplicates.head()))

중복된 ID 상위 5개 별 중복된 개수 : order_id
fa65dad1b0e818e3ccc5cb0e39231352    29
ccf804e764ed5650cd8759557269dc13    26
285c2e15bebd4ac83635ccc563dc71f4    22
895ab968e7bb0d5659d16cd74cd1650c    21
fedcd9f7ccdc8cba3a18defedd1a5547    19
Name: payment_value, dtype: int64

### 첫번째 아이디의 데이터 값 살펴보기

In [53]:
duplicates = payments.groupby('order_id').count()

print(payments[payments['order_id']=='fa65dad1b0e818e3ccc5cb0e39231352'].sort_values(by='payment_sequential'))

                                order_id  payment_sequential payment_type  \
14321   fa65dad1b0e818e3ccc5cb0e39231352                   1      voucher
23074   fa65dad1b0e818e3ccc5cb0e39231352                   2      voucher
65641   fa65dad1b0e818e3ccc5cb0e39231352                   3      voucher
9985    fa65dad1b0e818e3ccc5cb0e39231352                   4      voucher
28330   fa65dad1b0e818e3ccc5cb0e39231352                   5      voucher
29648   fa65dad1b0e818e3ccc5cb0e39231352                   6      voucher
82593   fa65dad1b0e818e3ccc5cb0e39231352                   7      voucher
68853   fa65dad1b0e818e3ccc5cb0e39231352                   8      voucher
17274   fa65dad1b0e818e3ccc5cb0e39231352                   9      voucher
19565   fa65dad1b0e818e3ccc5cb0e39231352                  10      voucher
32519   fa65dad1b0e818e3ccc5cb0e39231352                  11      voucher
73537   fa65dad1b0e818e3ccc5cb0e39231352                  12      voucher
77885   fa65dad1b0e818e3ccc5cb0e39231352                  13      voucher
36822   fa65dad1b0e818e3ccc5cb0e39231352                  14      voucher
63369   fa65dad1b0e818e3ccc5cb0e39231352                  15      voucher
78050   fa65dad1b0e818e3ccc5cb0e39231352                  16      voucher
79670   fa65dad1b0e818e3ccc5cb0e39231352                  17      voucher
80321   fa65dad1b0e818e3ccc5cb0e39231352                  18      voucher
74721   fa65dad1b0e818e3ccc5cb0e39231352                  19      voucher
93337   fa65dad1b0e818e3ccc5cb0e39231352                  20      voucher
74239   fa65dad1b0e818e3ccc5cb0e39231352                  21      voucher
100606  fa65dad1b0e818e3ccc5cb0e39231352                  22      voucher
85166   fa65dad1b0e818e3ccc5cb0e39231352                  23      voucher
99213   fa65dad1b0e818e3ccc5cb0e39231352                  24      voucher
24879   fa65dad1b0e818e3ccc5cb0e39231352                  25      voucher
79587   fa65dad1b0e818e3ccc5cb0e39231352                  26      voucher
4885    fa65dad1b0e818e3ccc5cb0e39231352                  27      voucher
39111   fa65dad1b0e818e3ccc5cb0e39231352                  28      voucher
39108   fa65dad1b0e818e3ccc5cb0e39231352                  29      voucher

        payment_installments  payment_value
14321                      1           3.71
23074                      1           8.51
65641                      1           2.95
9985                       1          29.16
28330                      1           0.66
29648                      1           5.02
82593                      1           0.32
68853                      1          26.02
17274                      1           1.08
19565                      1          12.86
32519                      1           4.03
73537                      1           3.60
77885                      1           0.00
36822                      1           0.00
63369                      1          14.04
78050                      1          12.86
79670                      1           3.72
80321                      1           0.73
74721                      1           5.02
93337                      1         150.00
74239                      1           4.11
100606                     1           4.03
85166                      1          18.86
99213                      1           0.42
24879                      1           3.68
79587                      1          28.27
4885                       1          66.02
39111                      1          29.05
39108                      1          19.26

In [59]:
payments2 = payments.drop_duplicates('order_id',False)

In [63]:
print(payments.nunique())
print(payments2.nunique())

order_id                99440
payment_sequential         29
payment_type                5
payment_installments       24
payment_value           29077
dtype: int64
order_id                96479
payment_sequential          2
payment_type                5
payment_installments       24
payment_value           27119
dtype: int64

In [66]:
print(payments2[payments2['order_id']=='ccf804e764ed5650cd8759557269dc13'].sort_values(by='payment_sequential'))

Empty DataFrame
Columns: [order_id, payment_sequential, payment_type, payment_installments, payment_value]
Index: []

## 하나로 합쳐진 데이터 불러오기

In [46]:
total_df = pd.read_csv('total_df.csv')

/Users/YiYoung/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3018: DtypeWarning: Columns (14,16,17,25,29,30,33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [47]:
total_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116584 entries, 0 to 116583
Data columns (total 55 columns):
Unnamed: 0                       116581 non-null float64
order_id                         116584 non-null object
customer_id                      116584 non-null object
order_status                     116584 non-null object
order_purchase_timestamp         116584 non-null object
order_approved_at                116570 non-null object
order_delivered_carrier_date     115371 non-null object
order_delivered_customer_date    114069 non-null object
order_estimated_delivery_date    116584 non-null object
order_item_id                    116584 non-null float64
product_id                       116584 non-null object
seller_id                        116584 non-null object
price                            116584 non-null float64
freight_value                    116584 non-null float64
payment_sequential               116584 non-null object
payment_type                     116584 non-null object
payment_installments             116584 non-null object
payment_value                    116584 non-null object
review_id                        116584 non-null object
review_score                     116584 non-null float64
review_comment_title             13999 non-null object
review_comment_message           49881 non-null object
review_creation_date             116581 non-null object
review_answer_timestamp          116581 non-null object
customer_unique_id               116581 non-null object
customer_zip_code_prefix         116581 non-null object
customer_city                    116581 non-null object
customer_state                   116581 non-null object
product_name_lenght              116581 non-null float64
product_description_lenght       116581 non-null object
product_photos_qty               116581 non-null object
product_weight_g                 116580 non-null float64
product_length_cm                116580 non-null float64
product_height_cm                116580 non-null object
product_width_cm                 116577 non-null float64
product_category_name_english    116578 non-null object
seller_zip_code_prefix           116578 non-null float64
seller_city                      116578 non-null object
seller_state                     116578 non-null object
geolocation_state_x              116578 non-null object
geolocation_lat_x                116578 non-null float64
geolocation_lng_x                116578 non-null float64
state_x                          116578 non-null object
geolocation_city_x               116505 non-null object
c_lat_x                          116505 non-null float64
c_lng_x                          116505 non-null float64
city_x                           116505 non-null object
geolocation_state_y              116578 non-null object
geolocation_lat_y                116578 non-null float64
geolocation_lng_y                116578 non-null float64
state_y                          116578 non-null object
geolocation_city_y               114874 non-null object
c_lat_y                          114874 non-null float64
c_lng_y                          114874 non-null float64
city_y                           114874 non-null object
dtypes: float64(18), object(37)
memory usage: 48.9+ MB

In [48]:
total_df.head()

,Unnamed: 0,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,...,c_lng_x,city_x,geolocation_state_y,geolocation_lat_y,geolocation_lng_y,state_y,geolocation_city_y,c_lat_y,c_lng_y,city_y
0,0.0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,...,-46.633242,sao paulo,SP,-23.155308,-47.084074,sp,maua,-23.669994,-46.448909,maua
1,1.0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,...,-46.633242,sao paulo,SP,-23.155308,-47.084074,sp,maua,-23.669994,-46.448909,maua
2,2.0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,...,-46.633242,sao paulo,SP,-23.155308,-47.084074,sp,maua,-23.669994,-46.448909,maua
3,3.0,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,delivered,2017-08-15 18:29:31,2017-08-15 20:05:16,2017-08-17 15:28:33,2017-08-18 14:44:43,2017-08-28 00:00:00,1.0,...,-46.633242,sao paulo,SP,-23.155308,-47.084074,sp,maua,-23.669994,-46.448909,maua
4,4.0,0e7e841ddf8f8f2de2bad69267ecfbcf,26c7ac168e1433912a51b924fbd34d34,delivered,2017-08-02 18:24:47,2017-08-02 18:43:15,2017-08-04 17:35:43,2017-08-07 18:30:01,2017-08-15 00:00:00,1.0,...,-46.633242,sao paulo,SP,-23.155308,-47.084074,sp,maua,-23.669994,-46.448909,maua